### ISSUE TITLE
Connection via pwa

### ISSUE THREAD

**Issue by TheHatBoxGhost** [Atlantis-Software/node-ptouch#1]
I love the simplicity of this code, however i can not use 'net' in the PWA I'm using. Any ideas how i could use my app to comunicate to the printer via bluetooth?

**Comment by atiertant** [comment]
hi, what is PWA ?

**Comment by TheHatBoxGhost** [comment]
> hi, what is PWA ?

Sorry, PWA is Progressive Web App. Although that is not really the core issue. I am trying to basically control the printer via a website I produced using vue.js or more to the point Quasar. 

The error I get is: "TypeError: net.Socket is not a constructor"

From my research, it makes sense that a website can not connect to an IP address. I am looking into if I can communicate directly via Bluetooth using the Bluetooth API. 

I'm trying to use the QL-820NWB FYI. Thanks for getting back to me anyways.

**Comment by atiertant** [comment]
i think this should be possible but i don't haveany idea on how it is possible...
you could try to sniff bluetooth traffic on a working application and trying to reproduce it.
did you found any spec on QL-820NWB FYI with bluetooth ?

**Comment by TheHatBoxGhost** [comment]
I will continue to test and let you know if i find a solution

**Comment by atiertant** [comment]
thanks
